version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "The total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        description: "The unique customer id for this table"
        tests:
          - unique
          - not_null
      - name: c_name
        description: "The customer name for this table"
        tests:
          - unique
          - not_null
      - name: c_nationkey
        description: "The nation key for this table"
        tests:

  - name: snowflake_nation_customer_count
    description: "The total number of customers for each nation in snowflake sample data"
    columns:
      - name: n_name
        description: "The nation name for this table"
        tests:
          - unique
          - not_null
      - name: n_nationkey
        description: "The nation key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_cumulative_orders_by_date
    description: "The cumulative sales by order date in snowflake sample data"
    columns:
      - name: o_orderdate
        description: "The order date"
        tests:
          - unique
          - not_null
      - name: o_totalprice
        description: "The sales for that date for a specific order"
        tests:

  - name: snowflake_customer_order_count
    description: "The count of orders by customer in snowflake sample data"
    columns:
      - name: c_custkey
        description: "The customer key"
        tests:
          - unique
          - not_null
      - name: c_name
        description: "The name of the customer"
        tests:

  - name: snowflake_100_customer_list
    description: "The first 100 customers in snowflake sample data"
    columns:
      - name: c_customer_sk
        description: "The customer sk"
        tests:
      - name: c_salutation
        description: "The customer salutation"
        tests:
      - name: c_first_name
        description: "The customer first name"
        tests:
      - name: c_last_name
        description: "The customer last name"
        tests:
      - name: c_email_address
        description: "The customer email"
        tests:
      - name: c_preferred_cust_flag
        description: "Boolean preferred customer"
        tests:
      - name: c_birth_day
        description: "Birth day"
        tests:
      - name: c_birth_month
        description: "Birth month"
        tests:
      - name: c_birth_year
        description: "Birth year"
        tests:

  - name: playing_with_tests
    description: "The entire customer table for playing with tests from snowflake sample data"
    columns:
      - name: c_custkey
        tests:
          - not_null
          - unique
      - name: c_mktsegment
        tests:
          - accepted_values:
              values:
                [
                  "BUILDING",
                  "AUTOMOBILE",
                  "MACHINERY",
                  "HOUSEHOLD",
                  "FURNITURE",
                ]

sources:
  - name: sample
    database: snowflake_sample_data # Tell dbt to look for the source in the "raw" database
    schema: tpch_sf1 # You wouldn't put your source data in public, would you?
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
